name: Build and Test Android App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build app
      run: flutter build apk --release

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk-build
        path: build/app/outputs/flutter-apk/app-release.apk

  download:
    name: Download artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: apk-build
        path: build
