# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-android-apk:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      fiicener.apk: build/app/outputs/apk/release/app-release.apk
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install pre-requirements
        run: sudo apt install clang curl pkg-config ninja-build cmake libblkid-dev libgtk-3-dev

      # Runs a set of commands using the runners shell
      - name: Install Android SDK and flutter
        run: |
          sudo apt install android-sdk openjdk-17-jdk
          sudo cp -rf /usr/lib/android-sdk ~/
          sudo chown -R $(id -u):$(id -g) ~/android-sdk 
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-*.zip
          mkdir -p ~/android-sdk/cmdline-tools/latest
          mv ~/cmdline-tools/* ~/android-sdk/cmdline-tools/latest/
          # JDK
          JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
          export JAVA_HOME
          PATH=$PATH:$JAVA_HOME/bin
          export PATH
          # android sdk
          export ANDROID_HOME=${HOME}/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools/bin
          # flutter
          git clone https://github.com/flutter/flutter.git
          export PATH=$PATH:$PWD/flutter/bin
          flutter doctor

      # Build Android SDK
      - name: Build Android APK
        run: |
          JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
          export JAVA_HOME
          PATH=$PATH:$JAVA_HOME/bin
          export PATH
          export ANDROID_HOME=${HOME}/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools/bin
          export PATH=$PATH:$PWD/flutter/bin
          flutter build apk --release
